echo MAKE environment configuration BASH script.
echo It creates following files: Makefile, config.makefile.
echo It is to be called from directory above src/github.com/curoles/fixhref.

command -v go >/dev/null 2>&1 || {
    echo >&2 "***Error: 'go' is required but it's not installed. Aborting."; exit 1;
}

echo "Go version: $(go version)"

SOURCE_PATH="$(dirname ${BASH_SOURCE[0]})"
echo Path to directory with source files: $SOURCE_PATH

ABS_SOURCE_PATH=$(realpath $SOURCE_PATH)
echo Absolute path to directory with source files: $ABS_SOURCE_PATH

CWD=$(pwd)
echo Current working directory: $CWD

MAKE_CONFIG="config.makefile"
touch $MAKE_CONFIG
echo "# Autogenerated MAKE configuration" > $MAKE_CONFIG
echo "SOURCE_PATH:=$SOURCE_PATH" >> $MAKE_CONFIG

MAKEFILE="Makefile"
touch $MAKEFILE

echo "include $MAKE_CONFIG" > $MAKEFILE
echo "-include custom.config.makefile" >> $MAKEFILE
echo "include $SOURCE_PATH/Makefile" >> $MAKEFILE
